<?php

use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_theme().
 */
function media_player_module_theme() {
  return array(
    'media_file_formatter' => array(
      'variables' => array('item' => NULL, 'item_attributes' => NULL, 'url' => NULL),
    ),
  );
}


/**
 * Implements template_preprocess_media_file_formatter().
 */
function template_preprocess_media_file_formatter(&$vars) {
 //template_preprocess_media_formatter($vars);
}
